Task10 done
nikmalevich/MyTwitter pull request #10
Opened 2020-04-27 13:04 UTC by nikmalevich

Use only the Latin alphabet, since there is no font for the Cyrillic alphabet. Uploading photos is not possible because this is not in the task. For login information, see the Controller class in the _users field.

2020-04-29 13:18 UTC, MaksimViarenich commented
I wanna cry
![Снимок экрана 2020-04-29 в 16 18 02](https://user-images.githubusercontent.com/60959134/80600417-09c49780-8a35-11ea-9050-f19e3a96e723.png)

2020-04-29 13:26 UTC, MaksimViarenich commented
Can't login. Error in console. Can't do anything

2020-04-29 13:27 UTC, MaksimViarenich requested changes
Sorry, can't check PR. Can't do anything

2020-05-01 12:44 UTC, nikmalevich commented
Can I call you on Skype? Everything starts up and works for me. I don’t know what could be the problem

2020-05-01 12:55 UTC, MaksimViarenich commented
> Can I call you on Skype? Everything starts up and works for me. I don’t know what could be the problem

Yes

2020-05-04 10:55 UTC, MaksimViarenich reviewed
Don't see where you set default number of posts
**Заполнение localStorage начальным набором твитов нужно сделать отдельным скриптом**

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/index.html
> +        <div id="logo" class="logo">
You don't need add class `logo` to `img` and `p` tags. One class for div is enough.
In CSS you can use selectors `.logo img` and `.logo p `

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/index.html
> +        <div class="log-in-out" id="log-in-out"><span id="username"></span><button class="log-in-out" id="logInOut">Log in</button></div>
Code style! It's not readable
```
<div class="log-in-out" 
     id="log-in-out">
    <span id="username"></span>
    <button class="log-in-out" 
            id="logInOut">
        Log in
    </button>
</div>
```

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/index.html
> +                <button class="add-post" id="addPost">add Post</button>
the same class for all tags is not needed. Add class `filters` just to `form` tag.
In CSS use selectors: `form.filters` `form.filters p` `form.filters label` `form.filters input`

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/view.js
> +    editPost(id = '', post = {}) {
Don't see usages for this method

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/model.js
> +    addAll(posts = []) {
Don't see usages for this method

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/model.js
> +    clear() {
Don't see usages for this method

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/model.js
> +            let post = JSON.parse(localStorage.getItem(keyPosts[i]));
Так как в локал сторедже может лежать и другая инфа, а вы обходите всю инфу в локал сторедже, то когда там встречается не JSON, то ваша прилага падает

Из задания: "Заполнение localStorage начальным набором твитов нужно сделать отдельным скриптом и заполнять localStorage при условии что localStorage **на старте пуст**. "

2020-05-04 10:55 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/controller.js
> +        }
Minor. Add empty line after `if`

2020-05-04 10:58 UTC, MaksimViarenich reviewed
When not logged in user will click to any filter and click Enter he will see window for adding new post
![Снимок экрана 2020-05-04 в 13 58 37](https://user-images.githubusercontent.com/60959134/80959377-61854900-8e0f-11ea-8d43-0621d9582b87.png)

2020-05-04 11:01 UTC, MaksimViarenich requested changes

2020-05-04 11:01 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/controller.js
> +    static logo(event) {
Don't see usages for `event` attribute. You can remove it

2020-05-04 11:01 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/controller.js
> +    static logInOut(event) {
Don't see usages for `event` attribute. You can remove it

2020-05-04 11:01 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/controller.js
> +    static donePost(event) {
Don't see usages for `event` attribute. You can remove it

2020-05-04 11:01 UTC, MaksimViarenich commented on task8/TutterApp/src/main/webapp/resources/js/controller.js
> +    static seeMore(event) {
Don't see usages for `event` attribute. You can remove it

2020-05-11 12:00 UTC, MaksimViarenich approved these changes

2020-05-11 12:03 UTC, MaksimViarenich reviewed
Where is the file for setting a default number of twists?

2020-05-11 12:03 UTC, MaksimViarenich commented
> Where is the file for setting a default number of twists?

Заполнение localStorage начальным набором твитов нужно сделать отдельным скриптом

2020-05-11 12:32 UTC, merged