Task3 done
nikmalevich/MyTwitter pull request #3
Opened 2020-03-02 17:54 UTC by nikmalevich

2020-03-02 20:39 UTC, MaksimViarenich commented
In general, it's good, just need to do some fixes to do it better.
You can ask any questions.

2020-03-02 21:21 UTC, nikmalevich commented
Can I ask in lesson?

2020-03-03 16:52 UTC, MaksimViarenich commented
Read, please, about `<form>`

2020-03-03 16:55 UTC, MaksimViarenich commented
Add logic for delete/edit

2020-03-03 17:32 UTC, MaksimViarenich requested changes

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/index.html
> +			<div class="logInOut">
For complex class name we use `-` as separator.
`logInOut` -> `log-in-out`

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/styles.css
> +	position: absolute;
In general it's bad practice to use `absolute` position, try to work with `relative`

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/styles.css
> +	border-width: 2;
2**px**

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/index.html
> +		<footer>
Better to move it to bottom. After <main></main>

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/index.html
> +<!DOCTYPE html>
Try to change the height of the window, you will see this:
<img width="1440" alt="Снимок экрана 2020-03-02 в 23 33 21" src="https://user-images.githubusercontent.com/60959134/75715320-43e81600-5cde-11ea-8e91-485b4dbd114f.png">

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/index.html
> +<!DOCTYPE html>
And width also)
<img width="1440" alt="Снимок экрана 2020-03-02 в 23 34 56" src="https://user-images.githubusercontent.com/60959134/75715436-74c84b00-5cde-11ea-8065-18af114ff87a.png">

2020-03-03 17:32 UTC, MaksimViarenich commented on UI/styles.css
> +	margin-left: 10%;
margin: 10px 0 0 10%;

2020-03-09 17:47 UTC, MaksimViarenich approved these changes

2020-03-09 17:47 UTC, MaksimViarenich commented on UI/styles.css
> +	margin: 5px 0 5px 0;
margin: 5px 0;

2020-03-09 17:47 UTC, MaksimViarenich commented on UI/styles.css
> +button.edit {
You can create one class for these buttons because they have the same style.

2020-03-09 18:57 UTC, merged